# Generated by Django 2.1 on 2018-08-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180824_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_code',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
