# Generated by Django 2.1 on 2018-08-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_download_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accounts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
