# Generated by Django 2.1 on 2018-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accounts',
        ),
        migrations.AddField(
            model_name='order',
            name='accounts',
            field=models.ManyToManyField(to='accounts.Account'),
        ),
    ]
