# Generated by Django 2.1 on 2018-08-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180826_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accounts',
        ),
    ]
