# Generated by Django 2.1 on 2018-08-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_order_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order'),
        ),
    ]
