# Generated by Django 2.1 on 2018-08-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order'),
        ),
    ]
