# Generated by Django 2.1 on 2018-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180826_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Аккаунты выданы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_comment',
            field=models.CharField(max_length=20, verbose_name='Qiwi примечание'),
        ),
    ]
