# Generated by Django 2.1 on 2018-08-28 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180827_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название группы')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='accounttype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
