# Generated by Django 2.1 on 2018-08-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180828_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountTypeGroup'),
        ),
    ]
