# Generated by Django 2.1 on 2018-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accounttypegroup_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttypegroup',
            name='types',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='group',
        ),
        migrations.DeleteModel(
            name='AccountTypeGroup',
        ),
    ]
